name = "charismabeauty"
compatibility_date = "2026-05-27"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "CHARISMA_DB"
database_id = "462bb574-db46-4cb6-a24b-f00ba1033e71"
